from enum import Enum 

FPS = 30
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
PINK = (252,70,236)
BALL_SPEED = 12
PADDLE_SPEED = 17
COMP_SPEED = 10
MAX_SPEED_INC = 6
SPEED_MULT = 0.5
MIN_ANGLE = 20
COUNTDOWN_NUM_WIDTH = 21
NUM_PARTICLES = 7
FRAME_SCALE = 0.7
WIN_SCORE = 7
WIDTH, HEIGHT = 800, 600

BORDER_WIDTH = 100
BORDER_HEIGHT = 200
SCREEN_WIDTH = BORDER_WIDTH + WIDTH
SCREEN_HEIGHT = BORDER_HEIGHT + HEIGHT
LEFT_SCREEN_OFFSET = BORDER_WIDTH / 2
TOP_SCREEN_OFFSET = 25
BOTTOM_SCREEN_OFFSET = BORDER_HEIGHT - TOP_SCREEN_OFFSET
BORDER_THICKNESS = 3

CAMERA_WIDTH = 300
CAMERA_HEIGHT = 170
PAUSE_DIST = 0.3

DEFAULT_FONT_SIZE = 36
SELECTED_FONT_SIZE = 46
TITLE_FONT_SIZE = 56
BAYSHORE_ADJ = 20

options = ["Classic", "Infinite", "Two Player", "Exit"]

class State(Enum):
    MENU = 0
    CLASSIC = 1
    INFINITE = 2
    PVP = 3
    EXIT = 4