from enum import Enum 

FPS = 30

WIDTH, HEIGHT = 800, 600
BORDER_WIDTH = 100
BORDER_HEIGHT = 200
SCREEN_WIDTH = BORDER_WIDTH + WIDTH
SCREEN_HEIGHT = BORDER_HEIGHT + HEIGHT
LEFT_SCREEN_OFFSET = BORDER_WIDTH / 2
TOP_SCREEN_OFFSET = 25
BOTTOM_SCREEN_OFFSET = BORDER_HEIGHT - TOP_SCREEN_OFFSET
BORDER_THICKNESS = 3
GAME_BOTTOM = SCREEN_HEIGHT - BOTTOM_SCREEN_OFFSET
GAME_TOP = TOP_SCREEN_OFFSET
PADDLE_WIDTH = 20
PADDLE_HEIGHT = 100
TOP_PADDLE_OFFSET = 50
HORIZ_PADDLE_OFFSET = 50
BALL_RADIUS = 15

CAMERA_WIDTH = 300
CAMERA_HEIGHT = 170
PAUSE_DIST = 0.3

PADDLE_SPEED = 17
COMP_SPEED = 10
NUM_PARTICLES = 7
FRAME_SCALE = 0.7
WIN_SCORE = 7
BALL_SPEED = 12
MAX_SPEED_INC = 6
MAX_ENERGY = 35**2
INFINITE_SLOW_DOWN = 0.6
SPEED_MULT = 0.5

POWER_UP_SPEED = 5
POWER_UP_RAD = 8
MIN_ANGLE = 20
SLOW_FACTOR = 0.1
SLOW_TIME = 1.5 * 1000
FREEZE_TIME = 2.5 * 1000
GRAB_TIME = 4 * 1000
DEGREE_INC = 5
PHI_MIN = 20
PHI_MAX = 160
STUCK_LINE_LENGTH = 40
HAND_OPEN_THRESH = 0.045

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
PINK = (252,70,236)
ICE_BLUE = (115, 155, 208)
SLIME_GREEN = (188, 233, 84)
LIGHT_GREY = (150, 150, 150)

DEFAULT_FONT_SIZE = 36
SELECTED_FONT_SIZE = 46
TITLE_FONT_SIZE = 56
BAYSHORE_ADJ = 20
COUNTDOWN_NUM_WIDTH = 21

options = ["Classic", "Infinite", "Two Player", "Arcade", "Double Trouble - Beta","Exit"]

class State(Enum):
    MENU = 0
    CLASSIC = 1
    INFINITE = 2
    PVP = 3
    ARCADE = 4
    DOUBLE = 5
    EXIT = 6

class PowerUpType(Enum):
    NONE = 0
    SLOW = 1
    FREEZE = 2
    GRAB = 3

PowerUpColour = {PowerUpType.SLOW : LIGHT_GREY, 
                 PowerUpType.FREEZE : ICE_BLUE,
                 PowerUpType.GRAB : SLIME_GREEN}
